#############################################################################
# Makefile for building relief.exe
# Generated by tmake at 17:29, 2004/10/08
#     Project: relief.pro
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	cl
CXX	=	cl
CFLAGS	=	-nologo -DCGAL_USE_GMP
CXXFLAGS=	-nologo -GR -GX -DCGAL_USE_GMP
INCPATH	=	-IC:\GtkGLExt\1.0\include\gtkglext-1.0 -IC:\GtkGLExt\1.0\lib\gtkglext-1.0\include -IC:\Gtk\2.0\include\gtk-2.0 -IC:\Gtk\2.0\lib\gtk-2.0\include -IC:\Gtk\2.0\include\atk-1.0 -IC:\Gtk\2.0\include\pango-1.0 -IC:\Gtk\2.0\include\glib-2.0 -IC:\Gtk\2.0\lib\glib-2.0\include -IC:\CGAL-3.0.1\auxiliary\wingmp\gmp-4.1.2\msvc -IC:\CGAL-3.0.1\include\CGAL\config\msvc7 -IC:\CGAL-3.0.1\include -ID:\home\dbourgui\src\utils
LINK	=	link
LFLAGS	=	/NOLOGO /incremental:no /SUBSYSTEM:console
LIBS	=	/libpath:C:\GtkGLExt\1.0\lib gtkglext-win32-1.0.lib gdkglext-win32-1.0.lib /libpath:C:\Gtk\2.0\lib gtk-win32-2.0.lib gdk-win32-2.0.lib atk-1.0.lib gdk_pixbuf-2.0.lib pangowin32-1.0.lib pangoft2-1.0.lib pango-1.0.lib gobject-2.0.lib gmodule-2.0.lib glib-2.0.lib intl.lib iconv.lib /libpath:C:\CGAL-3.0.1\lib\msvc7 CGAL.lib /libpath:C:\CGAL-3.0.1\auxiliary\wingmp\gmp-4.1.2\msvc gmp.lib opengl32.lib glu32.lib
MOC	=	$(QTDIR)\bin\moc.exe
UIC	=	$(QTDIR)\bin\uic.exe
REMOVE	=	-del
RMDIR	=	-rmdir /q /s
ZIP	=	zip -r -9

####### Files

HEADERS =	
SOURCES =	main.cc \
		application.cc \
		toolbox.cc \
		tool.cc \
		pencil_tool.cc \
		quill_tool.cc \
		brush_tool.cc \
		smudge_tool.cc \
		eraser_tool.cc \
		frisket_tool.cc \
		burnisher_tool.cc \
		scraper_tool.cc \
		tool_texture.cc \
		file.cc \
		drawing.cc \
		triangulation.cc \
		triangulation_display.cc \
		reconstruct_curve.cc \
		meshing.cc \
		tetrahedrization.cc \
		tetrahedrization_iostream.cc \
		tetrahedrization_display.cc \
		reconstruct_surface.cc \
		smooth_surface.cc \
		tesselation.cc \
		viewer.cc \
		debug.cc \
		images.c
OBJECTS =	main.obj \
		application.obj \
		toolbox.obj \
		tool.obj \
		pencil_tool.obj \
		quill_tool.obj \
		brush_tool.obj \
		smudge_tool.obj \
		eraser_tool.obj \
		frisket_tool.obj \
		burnisher_tool.obj \
		scraper_tool.obj \
		tool_texture.obj \
		file.obj \
		drawing.obj \
		triangulation.obj \
		triangulation_display.obj \
		reconstruct_curve.obj \
		meshing.obj \
		tetrahedrization.obj \
		tetrahedrization_iostream.obj \
		tetrahedrization_display.obj \
		reconstruct_surface.obj \
		smooth_surface.obj \
		tesselation.obj \
		viewer.obj \
		debug.obj \
		images.obj
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	relief.exe
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.C.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo$@ $<

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo$@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(REMOVE) $(TARGET) 
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<<
	    $(OBJECTS) $(OBJMOC) $(LIBS)
<<

moc: $(SRCMOC)

tmake: makefile

makefile: relief.pro
	tmake relief.pro -o makefile

dist:
	$(REMOVE) Makefile *.dsp *.dsw *.opt *.ncb *.mak

clean:
	$(REMOVE) $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	$(REMOVE) relief.opt

	$(RMDIR) Debug Release


####### Compile

main.obj: main.cc \
		application.hh

application.obj: application.cc \
		toolbox.hh \
		file.hh \
		drawing.hh \
		tool.hh \
		cgal_utils.hh \
		triangulation_display.hh \
		triangulation.hh \
		triangulation_base.hh \
		meshing.hh \
		tetrahedrization_display.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		tesselation.hh \
		tesselation_base.hh \
		viewer.hh \
		application.hh

toolbox.obj: toolbox.cc \
		images.h \
		application.hh \
		file.hh \
		pencil_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		quill_tool.hh \
		brush_tool.hh \
		smudge_tool.hh \
		eraser_tool.hh \
		frisket_tool.hh \
		burnisher_tool.hh \
		scraper_tool.hh \
		tool_texture.hh

tool.obj: tool.cc \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh

pencil_tool.obj: pencil_tool.cc \
		pencil_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh

quill_tool.obj: quill_tool.cc \
		quill_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh

brush_tool.obj: brush_tool.cc \
		tool_texture.hh \
		brush_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh

smudge_tool.obj: smudge_tool.cc \
		tool_texture.hh \
		smudge_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh

eraser_tool.obj: eraser_tool.cc \
		brush_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		eraser_tool.hh

frisket_tool.obj: frisket_tool.cc \
		brush_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		frisket_tool.hh

burnisher_tool.obj: burnisher_tool.cc \
		brush_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		burnisher_tool.hh

scraper_tool.obj: scraper_tool.cc \
		brush_tool.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		scraper_tool.hh

tool_texture.obj: tool_texture.cc \
		images.h \
		tool_texture.hh

file.obj: file.cc \
		application.hh \
		drawing.hh \
		file.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		triangulation_display.hh \
		triangulation.hh \
		triangulation_base.hh \
		meshing.hh \
		tetrahedrization_display.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		tesselation.hh \
		tesselation_base.hh \
		viewer.hh

drawing.obj: drawing.cc \
		application.hh \
		toolbox.hh \
		triangulation.hh \
		triangulation_base.hh \
		cgal_utils.hh \
		triangulation_display.hh \
		reconstruct_curve.hh \
		drawing.hh \
		file.hh \
		tool.hh

triangulation.obj: triangulation.cc \
		application.hh \
		triangulation.hh \
		triangulation_base.hh \
		cgal_utils.hh

triangulation_display.obj: triangulation_display.cc \
		triangulation_display.hh \
		triangulation.hh \
		triangulation_base.hh \
		cgal_utils.hh

reconstruct_curve.obj: reconstruct_curve.cc \
		reconstruct_curve.hh \
		triangulation.hh \
		triangulation_base.hh \
		cgal_utils.hh

meshing.obj: meshing.cc \
		application.hh \
		drawing.hh \
		file.hh \
		tool.hh \
		cgal_utils.hh \
		toolbox.hh \
		triangulation_display.hh \
		triangulation.hh \
		triangulation_base.hh \
		tetrahedrization_iostream.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		tetrahedrization_display.hh \
		smooth_surface.hh \
		reconstruct_surface.hh \
		meshing.hh \
		tesselation.hh \
		tesselation_base.hh

tetrahedrization.obj: tetrahedrization.cc \
		application.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		cgal_utils.hh

tetrahedrization_iostream.obj: tetrahedrization_iostream.cc \
		tetrahedrization_iostream.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		cgal_utils.hh

tetrahedrization_display.obj: tetrahedrization_display.cc \
		images.h \
		tetrahedrization_display.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		cgal_utils.hh

reconstruct_surface.obj: reconstruct_surface.cc \
		reconstruct_surface.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		cgal_utils.hh \
		debug.hh

smooth_surface.obj: smooth_surface.cc \
		smooth_surface.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		cgal_utils.hh

tesselation.obj: tesselation.cc \
		tesselation.hh \
		tesselation_base.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		cgal_utils.hh

viewer.obj: viewer.cc \
		application.hh \
		toolbox.hh \
		file.hh \
		drawing.hh \
		tool.hh \
		cgal_utils.hh \
		triangulation_display.hh \
		triangulation.hh \
		triangulation_base.hh \
		meshing.hh \
		tetrahedrization_display.hh \
		tetrahedrization.hh \
		tetrahedrization_base.hh \
		tesselation.hh \
		tesselation_base.hh \
		viewer.hh

debug.obj: debug.cc \
		debug.hh

images.obj: images.c \
		images.h

